FROM node:14.15.3-alpine3.10

RUN  apk update && \
 apk add git && \
 npm install -g npm

COPY . ./app/backend/api

WORKDIR /app/backend/api

RUN npm install

ENV APP_HOME /app/backend/api
ENV PATH ${APP_HOME}/node_modules/.bin:$PATH
ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo
ENV HOST 0.0.0.0
ENV PORT 8080

EXPOSE 8080

CMD [ "npm", "run", "start" ]