version: '3.7'

services: 
  db:
    env_file: ./docker/db/mysql.env
    environment:
      TZ: 'Asia/Tokyo'
    image: mysql:5.7
    container_name: db
    hostname: db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks: 
      - my-network
  frontend: 
    build: ./docker/frontend
    container_name: frontend
    env_file: ./frontend/ui/app.env
    environment: 
     - TZ=Asia/Tokyo
     - DEBUG=app:*
    volumes: 
     - ./frontend/ui:/app/frontend/ui
    tty: true
    depends_on: 
      - redis
    working_dir: /app/frontend/ui
    command: npm run dev
    ports: 
     - 3000:3000
    networks: 
     - my-network
  backend:
    build: ./docker/backend
    container_name: backend
    env_file: ./backend/api/app.env
    environment: 
     - TZ=Asia/Tokyo
     - DEBUG=app:*
    volumes: 
     - ./backend/api:/app/backend/api
    tty: true
    working_dir: /app/backend/api
    command: npm run start
    depends_on: 
      - db
    ports: 
     - 8080:8080
    networks: 
      - my-network
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    command: redis-server
    networks:
      - my-network
networks:
  my-network:
    external: true